apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgmp2022-swdp-cd-ci-deployment
spec:
  selector:
    matchLabels:
      app: jgmp2022-swdp-cd-ci-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: jgmp2022-swdp-cd-ci-deployment
    spec:
      containers:
      - name: jgmp2022-swdp-cd-ci-container
        image: luis03ragna/jgmp2022_swdp-cd-ci:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: jgmp2022-swdp-cd-ci-service
spec:
  selector:
    app: jgmp2022-swdp-cd-ci-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8081
    nodePort: 31110